/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as RecordingsIndexRouteImport } from './routes/recordings/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ErrorsStatusCodeIndexRouteImport } from './routes/_errors/$statusCode/index'
import { Route as AdminAbemaIndexRouteImport } from './routes/admin/abema/index'
import { Route as AdminNagisaIndexRouteImport } from './routes/admin/nagisa/index'
import { Route as AdminUnidentifiedIndexRouteImport } from './routes/admin/unidentified/index'
import { Route as AnimeIdIndexRouteImport } from './routes/anime/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/recordings/',
  path: '/recordings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsStatusCodeIndexRoute = ErrorsStatusCodeIndexRouteImport.update({
  id: '/_errors/$statusCode/',
  path: '/$statusCode/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAbemaIndexRoute = AdminAbemaIndexRouteImport.update({
  id: '/admin/abema/',
  path: '/admin/abema/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNagisaIndexRoute = AdminNagisaIndexRouteImport.update({
  id: '/admin/nagisa/',
  path: '/admin/nagisa/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnidentifiedIndexRoute = AdminUnidentifiedIndexRouteImport.update({
  id: '/admin/unidentified/',
  path: '/admin/unidentified/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdIndexRoute = AnimeIdIndexRouteImport.update({
  id: '/anime/$id/',
  path: '/anime/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/$statusCode/': typeof ErrorsStatusCodeIndexRoute
  '/admin/abema/': typeof AdminAbemaIndexRoute
  '/admin/nagisa/': typeof AdminNagisaIndexRoute
  '/admin/unidentified/': typeof AdminUnidentifiedIndexRoute
  '/anime/$id/': typeof AnimeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/browse': typeof BrowseIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/recordings': typeof RecordingsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/$statusCode': typeof ErrorsStatusCodeIndexRoute
  '/admin/abema': typeof AdminAbemaIndexRoute
  '/admin/nagisa': typeof AdminNagisaIndexRoute
  '/admin/unidentified': typeof AdminUnidentifiedIndexRoute
  '/anime/$id': typeof AnimeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/': typeof AdminIndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/_errors/$statusCode/': typeof ErrorsStatusCodeIndexRoute
  '/admin/abema/': typeof AdminAbemaIndexRoute
  '/admin/nagisa/': typeof AdminNagisaIndexRoute
  '/admin/unidentified/': typeof AdminUnidentifiedIndexRoute
  '/anime/$id/': typeof AnimeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/'
    | '/browse/'
    | '/changelog/'
    | '/recordings/'
    | '/settings/'
    | '/$statusCode/'
    | '/admin/abema/'
    | '/admin/nagisa/'
    | '/admin/unidentified/'
    | '/anime/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/browse'
    | '/changelog'
    | '/recordings'
    | '/settings'
    | '/$statusCode'
    | '/admin/abema'
    | '/admin/nagisa'
    | '/admin/unidentified'
    | '/anime/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/'
    | '/browse/'
    | '/changelog/'
    | '/recordings/'
    | '/settings/'
    | '/_errors/$statusCode/'
    | '/admin/abema/'
    | '/admin/nagisa/'
    | '/admin/unidentified/'
    | '/anime/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  RecordingsIndexRoute: typeof RecordingsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ErrorsStatusCodeIndexRoute: typeof ErrorsStatusCodeIndexRoute
  AdminAbemaIndexRoute: typeof AdminAbemaIndexRoute
  AdminNagisaIndexRoute: typeof AdminNagisaIndexRoute
  AdminUnidentifiedIndexRoute: typeof AdminUnidentifiedIndexRoute
  AnimeIdIndexRoute: typeof AnimeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/recordings'
      fullPath: '/recordings/'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_errors/$statusCode/': {
      id: '/_errors/$statusCode/'
      path: '/$statusCode'
      fullPath: '/$statusCode/'
      preLoaderRoute: typeof ErrorsStatusCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/abema/': {
      id: '/admin/abema/'
      path: '/admin/abema'
      fullPath: '/admin/abema/'
      preLoaderRoute: typeof AdminAbemaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nagisa/': {
      id: '/admin/nagisa/'
      path: '/admin/nagisa'
      fullPath: '/admin/nagisa/'
      preLoaderRoute: typeof AdminNagisaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unidentified/': {
      id: '/admin/unidentified/'
      path: '/admin/unidentified'
      fullPath: '/admin/unidentified/'
      preLoaderRoute: typeof AdminUnidentifiedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id/': {
      id: '/anime/$id/'
      path: '/anime/$id'
      fullPath: '/anime/$id/'
      preLoaderRoute: typeof AnimeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  RecordingsIndexRoute: RecordingsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ErrorsStatusCodeIndexRoute: ErrorsStatusCodeIndexRoute,
  AdminAbemaIndexRoute: AdminAbemaIndexRoute,
  AdminNagisaIndexRoute: AdminNagisaIndexRoute,
  AdminUnidentifiedIndexRoute: AdminUnidentifiedIndexRoute,
  AnimeIdIndexRoute: AnimeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
